### PR TITLE
Port Synth-lizard Markings

### PR DESCRIPTION
**Pull request by KittenColony**
## About the PR
More markings for synthetics, specifically lizards

## Why / Balance
More synth markings. Bloat? never heard of her

## Technical details
Ports several RSIs, adds them as markings

## Media
image

## Requirements

- [x] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:

- add: Added several new markings for Synthetic lizards

### CODE REVIEW

**Comment by KittenColony** [comment]
ill get images soon

**Comment by KittenColony** [comment]
no idea what the build failure is.

**Review by dffdff2423 — APPROVED** [review]
YAML looks fine. I cannot review art.

**Comment by KittenColony** [comment]
> YAML looks fine. I cannot review art.

sprites ported from Bubberstation / Skyrat

**Comment by dffdff2423** [comment]
Test failure is a Heisentest. I reran it.

**Comment by KittenColony** [comment]
last second commit because the back view for the tail cropped the leg when it didnt need to

**Comment by KittenColony** [comment]
works :)

**Pull request merged**
