### PR TITLE
Fix stupid chem names.

### PR DESCRIPTION
**Pull request by dffdff2423**
## About the PR

These names are confusing and stupid. If upstream ever changes the name of
these this PR should be reverted.

## Why / Balance

We talked about it in discord.

## Technical details

I just looked up a list of ss13 chems and copied a few that sounded good. If
you think they suck feel free to tell me to change it.

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

None

**Changelog**

:cl: Aquif
- The drug "Stimulants" has been renamed to "Hyperzine" and the drug "Space Drugs" has been renamed to "Space Mirage" in hopes of reducing confusion.

### CODE REVIEW

**Comment by Nairodian** [comment]
Colorspace sounds so out of place.

**Comment by dffdff2423** [comment]
I am the least creative person for this kind of stuff. Some options I have found on a list of ss13 drugs/the internet for "fake drug names":
- Mirage
- Contemplus
- Ephemerol
- Neocaine

**Comment by Nairodian** [comment]
Okay to hell with it we have a literal chemical called "happiness" I like the name Space Mirage.

**Review by Nairodian — APPROVED** [review]

**Comment by LankLTE** [comment]
I'd still like to at least try to have these renamed upstream post-freeze, but for now this is fine here.

**Pull request merged**
