### PR TITLE
Map patch for Bagel, Core, Marathon, and Meta

### PR DESCRIPTION
**Pull request by dffdff2423**
## About the PR

Adds a basic map patch that adds lost+found and a few more record
consoles to Bagel, Core, Marathon, and Meta.

## Why / Balance

Admins always forget

## Technical details

Map patch

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

bagel1
bagel2
core1
core2
marathon
meta1

## Breaking changes

**Changelog**

:cl: Aquif
- tweak:  Bagel, Core, Marathon, and Meta will have lost and found lockers automatically spawn. (credit to Moony for the map patch system)

### CODE REVIEW

**Comment by moonheart08** [comment]
Make sure to test the patches ingame (just in case my testing of the original PR was insufficient somehow), otherwise looks good.

**Comment by dffdff2423** [comment]
I tested them on all of the maps.

**Review by moonheart08 — APPROVED** [review]

**Comment by Nairodian** [comment]
> image

That's a fucking evil spot to put the locker since it'll block the firelock but I can't see anywhere else to put it.

**Comment by dffdff2423** [comment]
> That's a fucking evil spot to put the locker since it'll block the firelock but I can't see anywhere else to put it.

I did not even think of that. Worst case we can move it to the bridge.

**Comment by moonheart08** [comment]
> > That's a fucking evil spot to put the locker since it'll block the firelock but I can't see anywhere else to put it.
> 
> I did not even think of that. Worst case we can move it to the bridge.

It could be put next to the filing cabinet just fine.

**Comment by Nairodian** [comment]
I was thinking left of the "visitor" desk chair would work.

**Comment by dffdff2423** [comment]
After testing it I think putting it next to the filing cabinet looked better. 

image

**Comment by LankLTE** [comment]
I'd prefer to keep it out of the bridge if possible, but it is what it is.

**Comment by dffdff2423** [comment]
I could not really find any space in the HoP's room. They should be the only person with access to it anyways.

**Pull request merged**
