### PR TITLE
Updates Aspid

### PR DESCRIPTION
**Pull request by Aexxie**
adds robotics console to aspid

### CODE REVIEW

**Comment by Nairodian** [comment]
That file diff is insane, map moment.

**Review by Nairodian — APPROVED** [review]
I'm going to trust this does as it says and that's it because I literally can not easily check the difference.

**Comment by dffdff2423** [comment]
The test failure is related to the map changes.

**Comment by dffdff2423** [comment]
We should probably move aspid to our namespace as upstream is not maintaining it anymore (like we did with gemini).

**Comment by LankLTE** [comment]
Closing this, ask for it to be opened if you have intent to ever finish it.

**Pull request closed without merging**
