### PR TITLE
Aspid Dorms, Chapel, Bar, Festive, and Fixes Update

### PR DESCRIPTION
**Pull request by Nairodian**
## About the PR
- Entirely redoes dorms.
- Redoes the Chaplain's bedroom.
- Adds a vox box in the bar.
- Adjusts the maints bar.
- Gift tree in the bar.
- Fixes the chem spawn, CMO hardsuit, and salvage conveyer belt issues.
- Adjusts a couple of the role slots to not needlessly overfill some jobs.
- Other things that I'm probably forgetting.

## Media
Dorms + Chapel
image
##
Vox box + Festivities
image

### CODE REVIEW

**Comment by Nairodian** [comment]
I'm not actually sure what the test fail is on this one.

**Comment by dffdff2423** [comment]
IIRC that is a heisentest right now. I just reran it.

**Comment by Nairodian** [comment]
You know, I'm used to RobustToolbox being ignored by most things and not being a problem, so much so I didn't think twice about it being in the commit log. I have no idea if that'll cause issue, do let me know.

**Comment by dffdff2423** [comment]
Yeah, updating RT (outside of an upstream merge) causes a ton of issues.

**Pull request closed without merging**
