### PR TITLE
security plate carrier improvements

### PR DESCRIPTION
**Pull request by MilonPL**
## About the PR

adds the ClothingBlockSlotsOnEquipComponent to the plate carrier and makes it block outerClothing, while also giving it the same stats as the armor vest
makes it use the sec belt fill and changes the loadout to use the filled version

## Why / Balance

fixes https://github.com/cosmatic-drift-14/cosmatic-drift/issues/452

## Media

<details><summary>Click me!</summary>
<br>
gottem

image

image

</details>

### CODE REVIEW

**Comment by MilonPL** [comment]
FUCKING YAML I HATE YAML

**Comment by dffdff2423** [comment]
How hard would it be to add some indication in the UI (like MultiHandedItemComponent)?

**Comment by MilonPL** [comment]
> How hard would it be to add some indication in the UI (like MultiHandedItemComponent)?

it has a custom message when you try to equip it into a blocked slot, you could technically change the description to say "blocks X slots when worn" but im not sure how hard it would be

**Comment by MilonPL** [comment]
@dffdff2423 how's this?

image

**Review by dffdff2423 — APPROVED** [review]

**Review by Nairodian — APPROVED** [review]

**Pull request merged**
