### PR TITLE
Head of Secuirity Hardsuit Resprite

### PR DESCRIPTION
**Pull request by PursuitInAshes**
This PR is made on behalf of discord user "icestormthedragon", the section "About the PR" was written by them. All other content in this PR is my own (Excluding the spritework.). The original intent of this resprite was to have two new versions of the sprite be held in consideration, but I'm unable to finish mine at this time, so I still wanted to provide the opportunity for the sprite to be considered for use.

## About the PR/Why
The intention of the change is to have the HoS follow the general same black design of the other security hardsuits, well still looking unique and rich like the rest of the HoS outfits, the design of the HoS has always been something that bothered me, aswell as the red of the old helmet not fighting with the rest of security, and leading to some friendly fire issues (admittedly due to players lack of knowledge but, still became an issue sometimes), so the hardsuit helmet change should just help the HoS hardsuit to be more appealing in general for HoS players

## Technical details
N/A

## Media
Content Client_T22vkoRhgl
Content Client_eIcGmfp7Gr
Content Client_o6U5FYIeW0
Content Client_BWUaCPXxgk

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
tweak: The head of security hardsuit has been resprited.

### CODE REVIEW

**Comment by dffdff2423** [comment]
I have never really run into friendly fire issues with the old hardsuit (most of my HoS playtime is on salamander). I personally hate the helmet of the old HoS hardsuit. To me, it just felt like it did not fit in to the theme at all. I do like this version a bit better than the old one, although the yellow padding looks a bit out of place to me.

**Comment by Nairodian** [comment]
Despite I think being the one to suggest it, I do think the gold plate feels out of place. Hrmph. What about changing the white (not a HoS color) to like gold to match with the rest, maybe red?

**Comment by EdenTheLiznerd** [comment]
If your remove the gold pauldron I'd like it more personally, it's just offsetting from security and doesn't fit at all imo.

**Comment by Aexxie** [comment]
Gold pauldron would look better as a dark grey or maybe a dark red/maroon. White stripe would look far better as red

**Comment by Aexxie** [comment]
Additionally, (sorry I am really bad with thinking of everything I want to say BEFORE I comment), once those changes are made and reviewed, I'd like to see this on upstream

**Pull request merged**
