### PR TITLE
Reorganize roles and add warning about the two job rule

### PR DESCRIPTION
**Pull request by dffdff2423**
## About the PR

- **Recategorize jobs to fit their use on CD**
- **Warning about job rule for HumanoidProfileEditor**

## Why / Balance

This is just a ""temporary"" measure until somebody enforces this mechanically. See #347 

## Media

image

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Reorganize the character editor to make it clear what jobs are in what department for the "two department + service" rule

### CODE REVIEW

**Comment by Nairodian** [comment]
How does this look on the crew manifest, you know?

**Comment by dffdff2423** [comment]
image

**Comment by Nairodian** [comment]
Hm, I realize it's not too bad either way. Being able to quickly take a glance at the manifest and get a list of all the command members was nice, but perhaps just ask on the Discord what others think.

**Comment by LankLTE** [comment]
I'm with Nairod that it's nice to just be able to look and see every command member

**Comment by dffdff2423** [comment]
Then I think re-adding Command but then also adding "High Command" might be the best approach.

**Comment by dffdff2423** [comment]
Image of current state: 
image

**Pull request merged**
