### PR TITLE
Add CD CODEOWNERS

### PR DESCRIPTION
**Pull request by dffdff2423**
## About the PR
Adds a CODEOWNERS file. I have been currently using github notifications to keep track of what PRs need review, but this has become unsustainable due to the recent influx of PRs CD has been getting. This allows PRs that need review to show up in a nice list for me. I have intentionally excluded myself from PRs that exclusively contain mapping/art changes.

@Nairodian @LankLTE do ether of you want to be added to this list while I am working on it? If so, what files do you care about? You can also push to this branch directly.

### CODE REVIEW

**Comment by MilonPL** [comment]
make teams in your org instead then assign people to them instead of having to edit codeowners every time you get a new maint
image

**Comment by Nairodian** [comment]
> @Nairodian @LankLTE do ether of you want to be added to this list while I am working on it? If so, what files do you care about? You can also push to this branch directly.

Depends on how stupidly in-depth I can go, but was thinking something like: Rules & in-character documentation, mapping, roles & loadouts, and recipes probably.

As for Milon's comment, that's a Lank thing.

**Comment by LankLTE** [comment]
> make teams in your org instead then assign people to them instead of having to edit codeowners every time you get a new maint

I'm really not that concerned about it tbh it's not like we'll be hiring maints that much

**Comment by MilonPL** [comment]
It's way more convenient for the future than having to revisit it every time though

**Comment by dffdff2423** [comment]
Different maints might also care about different things and CD is operating on such a small scale anyways I don't think it matters much.

**Comment by LankLTE** [comment]
I'm going to look at everything anyways so I don't particularly care about being in this

**Pull request merged**
