### PR TITLE
Cosmatic Drip ~ INTERMISSION 1

### PR DESCRIPTION
**Pull request by KittenColony**
## About the PR
An intermission from the typical departmental drip updates. PR Adds two new jumpsuits in the form of the Casual Detective and Blue Formal suit, with matching jackets, and a red and blue bowtie.

## Why / Balance
Drip, need I say more?

## Technical details
RSI and YAML sprites, nothing out of the ordinary

## Media
image
image
image

## Requirements

- [x] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
- Added: New casual detective fatigues and matching Forensics Jacket, arriving, on the scene.
- Added: A blue formal suit and jacket, waistcoat can be folded away if desired.
- Added: Red and Blue bowties are now available in a threadvend near you.
- Added: Security now have their own departmental bandana and a new greatcoat.

### CODE REVIEW

**Review by dffdff2423 — APPROVED** [review]
I did not test in-game, but looks fine to me.

**Review by dffdff2423 — APPROVED** [review]
New additions seem fine

**Comment by KittenColony** [comment]
Greatcoat and bandana still needs loadouts / secdrobe

**Comment by KittenColony** [comment]
there we go :)

**Review by dffdff2423 — APPROVED** [review]

**Pull request merged**
