### PR TITLE
lost and found ui

### PR DESCRIPTION
**Pull request by MilonPL**
## About the PR

title
fixes, cleanup, major bullshittery
strips the character of their items, stores it in a container, updates the list in the LostAndFoundComponent to render the UI, works like upstream's cryo more or less
the locker isn't a locker anymore since it just opens the ui

## Why / Balance

Closes https://github.com/cosmatic-drift-14/cosmatic-drift/issues/443
Closes https://github.com/cosmatic-drift-14/cosmatic-drift/issues/444
Closes https://github.com/cosmatic-drift-14/cosmatic-drift/issues/457

## Media

<details><summary>Click me!</summary>
<br>

image

image

</details>

### CODE REVIEW

**Review by dffdff2423 — CHANGES_REQUESTED** [review]
I don't really see any major issues with the code. The only possible issue I see is that upstream station records are not being deleted, but that should not be a large deal.

Could you restrict the locker to only the captain and HoP like it was before?

**Comment by MilonPL** [comment]
> Could you restrict the locker to only the captain and HoP like it was before?

do you want me to lock the entire UI behind access using ActivableUIRequiresAccess or just limit who can retrieve items but make viewing available to everyone?

**Comment by dffdff2423** [comment]
> do you want me to lock the entire UI behind access using ActivableUIRequiresAccess or just limit who can retrieve items but make viewing available to everyone?

I don't really have a preference. Ether works.

**Review by dffdff2423 — APPROVED** [review]

**Comment by LankLTE** [comment]
Description (and maybe sprite eventually but less so) will probably need to be changed once other methods than cryosleeping exist but for now it doesn't matter.

**Pull request merged**
