### PR TITLE
Two-Tone lizard snouts

### PR DESCRIPTION
**Pull request by KittenColony**
## About the PR
Adds another lizard snout, based of the Sharp Snout, allowing for two customizable snout colours

## Why / Balance
There are only two lizard snouts and they both only allow for a basic level of customization

## Technical details
yml, ftl, rsi

## Media
image

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:

Add: Added a new lizard snout, featuring a split muzzle and snoot that can be coloured independently

### CODE REVIEW

**Comment by KittenColony** [comment]
hold off on merging since this is being PRed upstream

**Comment by KittenColony** [comment]
[Upstream ver.](https://github.com/space-wizards/space-station-14/pull/27143)

**Comment by KittenColony** [comment]
upstream was merged

**Comment by Nairodian** [comment]
Sweet, just await the next Upstream merge then.

**Pull request closed without merging**
