### PR TITLE
Gemini Maintenance Patch

### PR DESCRIPTION
**Pull request by MciReloaded**
## About the PR

- Added vents and scrubbers to the animal pens to stop them from suffocating 
- Changed Cloning out for a Psychology office 
- Added a Psychology job slot
- Moved a strangely placed fire extinguisher in the courtroom to stop criminals from breaking out
## Why / Balance

For the fire extinguisher, it was not intended to be accessible from the jail cell (I hope). For the others- cloning is not something that is guaranteed anymore, and keeping the space there would be needlessly wasteful when we could have more dedicated RP space on a larger station. And who wants to be a zoo keeper.... when your animals _**will**_  die.
## Media

image
Fire Extinguisher new placement
image
Updated Animal Pens
image
Psychology Office
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- add: Added Psychology Office!
- fix: Put vents and scrubbers in the animal pens. No more suffocating bees! 
- fix: Moved jail cell fire extinguisher. Sorry, criminals!

### CODE REVIEW

**Review by dffdff2423 — APPROVED** [review]
LGTM

**Comment by Nairodian** [comment]
There's a syndicate stamp somewhere on this map, I'm leaning towards we should remove that. I won't hold this PR back for that, always can be handled later on, but if you've got the time since you already have the PR open.

**Comment by MciReloaded** [comment]
Not a problem, fixing that is a lot easier since I can just open the thing and pull it. Not sure why packaging is failing, though?

**Comment by dffdff2423** [comment]
Was probably just a bug in the packaging script or github.

**Pull request merged**
