### PR TITLE
Scary bullets

### PR DESCRIPTION
**Pull request by Just-a-Unity-Dev**
## About the PR

Increases the base damage of bullets by Quite A Lot and adds bullet damage falloff (latter is TODO)

TODO:
- Bullet damage falloff
- Cooler looking bullets (tracers?)
- Laser damage needs tweaking

## Why / Balance

[The original thread I got this PR from](https://discord.com/channels/1163352113162768436/1237483795024969790/1237483795024969790), in summary:
- People with guns actually have to worry about landing their hits
- Warden has to consider *who* they're handing weapons to
- Makes running away from gunfire a real thing, since you cant get shot twice and just walk off to medbay like you didn't just get shot with a rifle

I'm not 100% sure about the slug being 65 damage; the anti-materiel rifle being 120 seems *fine-ish* to me since I really doubt a crewmember is gonna obtain a Hristov - and if they do, they probably deserve it.

## Technical details

Modifies upstream code.

## Requirements

- [x] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: rain
- tweak: Made guns more impactful.
- add: Bullets now lose damage over distance - getting shot point blank will be slightly lethal than getting shot from a range!

### CODE REVIEW

**Comment by Just-a-Unity-Dev** [comment]
I'd like to gather some thoughts on this since this turns a vast majority of ballistic weapons from 5-7 shots to 2-3 shots

**Comment by KittenColony** [comment]
if you could, do you think you could also make a system to mark if something is "fired" vs just thrust, stabbed or thrown?

Asking because Nairod and I were discussing armour for stabbings vs actual bulletproof vests. Just a system that could see if a hit was from a bullet or not, and then modify the incoming damage depending on if the armour _is_ or _isn't_ bulletproof

this is probably coming off as insane, lmk if you need me to re-write this

**Comment by Just-a-Unity-Dev** [comment]
TODO: vests, replace bullet damage with bullet velocity, essentially take base of rimworld CE's combat and put it here

**Comment by dffdff2423** [comment]
I like the idea of this, however I think you should wait until after newmed. I think it is still being worked on.

**Comment by Just-a-Unity-Dev** [comment]
no longer interested in ss14 development

**Pull request closed without merging**
